version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Node.js dependencies...
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - echo Building the Angular application...
      - ng build --prod

artifacts:
  files:
    - "**/*"
  base-directory: dist/
